### ISSUE TITLE
!Question! Project Future

### ISSUE THREAD

**Issue by ChrSch84** [anaelorlinski/OpenWrt-NanoPi-R5S-Builds#16]
Will this Project go on if there is a nativ OpenWRT support?

Because on the Nightly Builds OpenWRT is working but there is no "Shell" and no USB/Keyboard funktion.

Thank you

**Comment by anaelorlinski** [comment]
I think the OpenWrt official support will happen soon or later since patches are upstreamed in Linux kernel over time. If this is not too much work I will probably make it work with the next stable release (OpenWrt 24.xx) to try keeping the same level of features. Unfortunately I don't use this device as my main router so I have less interest updating this one on a regular basis.

**Comment by ChrSch84** [comment]
Thanks for the Info. Good for you bad for us  :)
