### ISSUE TITLE
Support for Atheros ar9271 (kmod-ath9k-htc)?

### ISSUE THREAD

**Issue by eryepa** [anaelorlinski/OpenWrt-NanoPi-R5S-Builds#18]
Hi! 

I don't understand it well, maybe i'm doing something wrong, I recently installed openWRT and am trying to figure it out, and because of [this](https://openwrt.org/meta/infobox/upgrade_packages_warning), I want to ask:

When I try to install kmod-ath9k-htc I get an error about the kernel version not matching:
Require version = 5.15.167-1-2d23b8a4ca7c461cce81c262d535bcf7,
installed 5.15.167-1-2b42d929ca1fdb8932a0cfddd0b706b8

![image](https://github.com/user-attachments/assets/bc1da06e-7cb8-4b37-a1b9-c45da6aab355)

```
# opkg install kmod-ath9k-htc
Unknown package 'kmod-ath9k-htc'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.167-1-2d23b8a4ca7c461cce81c262d535bcf7) for kmod-cfg80211
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-cfg80211 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.167-1-2d23b8a4ca7c461cce81c262d535bcf7) for kmod-mac80211
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-mac80211 found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.167-1-2d23b8a4ca7c461cce81c262d535bcf7) for kmod-ath
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ath found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.167-1-2d23b8a4ca7c461cce81c262d535bcf7) for kmod-ath9k-common
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ath9k-common found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.15.167-1-2d23b8a4ca7c461cce81c262d535bcf7) for kmod-ath9k-htc
 * pkg_hash_fetch_best_installation_candidate: Packages for kmod-ath9k-htc found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package kmod-ath9k-htc.
```
How can i solve this?

**Comment by anaelorlinski** [comment]
Hi!
Unfortunately there is no easy solution to fix this immediately, this is a current limitation of my builds (and of all custom OpenWRT builds in general) : packages that bundle kernel modules fail to install because of different kernel vermagic.
-The cleanest solution for your purpose would be to fork my repo and edit the .seed files to add your extra packages at build time that depend on kernel modules.
-You can also give a try with OpenWRT snapshots I think they support r5s now (but you also need to install all the kernel packages the same day because the builds are changed every day).
-To fix my build the possible solution I could implement would be to manually build some specific packages and add them into the image so there is an available kernel compatible build. I might give a try within the next couple of days.
